# Generated by Django 3.0.7 on 2020-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200624_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='signature',
            field=models.CharField(default='他很懒，什么都没有留下。', max_length=50),
        ),
    ]
