# Generated by Django 3.0.7 on 2020-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200624_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='signature',
            field=models.CharField(default='这个人并没有注意到个人简介这个功能，真遗憾', max_length=50),
        ),
    ]
