# Generated by Django 3.0.7 on 2020-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200624_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uuid',
        ),
        migrations.AddField(
            model_name='users',
            name='GID',
            field=models.IntegerField(default=258805783),
        ),
    ]
