# Generated by Django 3.0.7 on 2020-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200624_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='GID',
            field=models.IntegerField(default=173775437),
        ),
    ]
